develop-1
alexlzrv/go-mart pull request #1
Opened 2023-07-21 17:05 UTC by alexlzrv

2023-07-25 20:45 UTC, alexlzrv commented
@s-shpak не совсем понимаю почему у меня контекст закрывается

2023-07-31 10:32 UTC, alexlzrv commented
@s-shpak в чем может быть проблема с context?

2023-07-31 15:21 UTC, s-shpak requested changes
1. Автотесты пока не проходят
2. В проекте нет ни одного юнит-теста
3. Почеу ты нигде не использовал сжатие ответа/декомпрессию запроса?

2023-07-31 15:21 UTC, s-shpak commented on .github/workflows/golangci-lint.yml
> +name: golangci-lint
`golangci-lint` должен использовать конфигурацию отсюда: https://github.com/s-shpak/praktikum-golangci-lint

2023-07-31 15:21 UTC, s-shpak commented on internal/config/config.go
> +	if err := env.Parse(&cfg); err != nil {
Ошибка должна обрабатываться

2023-07-31 15:21 UTC, s-shpak commented on internal/config/config.go
> +	accrualAddressDefault
Предполагается, что у сервиса нет адреса по умолчанию?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/gophermart.go
> +	if err != nil {
Ошибка должна обрабатываться: лучше всего было бы прокинуть ее наверх, и там вызвать `Fatal` логгера. Для этого логгер придется инициализировать на уровне выше

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/gophermart.go
> +	pg, err := sql.NewPostgresStorage(cfg.DSN, log)
1. Важно ли нам знать, что `storage` делает запросы к Postgres?
2. Когда ты передаешь логгер в компонент, было бы хорошо создать дочерний логгер, который автоматически бы добавлял информацию о том, какой компонент его вызывает

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/gophermart.go
> +		log.Errorf("Error init postgres storage %s", err)
Необходимо ли продолжать выполнение после возникновения этой ошибки?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/gophermart.go
> +	if err = r.Run(ctx); err != nil {
Graceful shutdown не реализован: graceful shutdown должен также закрывать соединение к БД и останавливать `loyaltyAccrual`. При этом основная горутина должна дожидаться корректного завершения всех компонентов

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/gophermart.go
> +		if err != nil {
Эту ошибку надо как-то обработать

2023-07-31 15:21 UTC, s-shpak commented on sql/postgres.go
> +		log.Errorf("attempt to establish connection failed: %s", err)
Зачем логировать ошибку здесь, если ты прокидываешь ее наверх?

2023-07-31 15:21 UTC, s-shpak commented on sql/postgres.go
> +	*sql.DB
Почему ты втраиваешь этот объект в `Postgres`, почему бы не определить его как поле?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/gophermart.go
> +	repo := pgrepo.NewRepository(pg, log)
Почему бы не спрятать логику инициализации подключения к БД внутрь этого конструктора?

2023-07-31 15:21 UTC, s-shpak commented on sql/postgres.go
> +	db, err := sql.Open("pgx", dsn)
Лучше использовать пул соединений

2023-07-31 15:21 UTC, s-shpak commented on sql/migrations/00001_init.up.sql
> +                        status TEXT,
Почему это поле может быть `NULL`?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/rest/middleware/jwtauth.go
> +		w.Header().Add("Authorization", tokenHeader)
Для хранения таких значений обычно используется контекст запроса. Ключи надо определять с помощью йоты: https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/rest/middleware/jwtauth.go
> +var key = []byte("secret")
То есть ключ всегда один и тот же?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/rest/middleware/jwtauth.go
> +	j "github.com/alexlzrv/go-mart/internal/utils/jwt"
Зачем этот alias ?

2023-07-31 15:21 UTC, s-shpak commented on internal/loyalty-accruals/loyalty-accruals.go
> +	client := http.Client{}
1. Зачем создавать каждый раз новый клиент?
2. Клиент должен делать ретрай при возникновении "случайных" ошибок на стороне `accrual`: https://github.com/hashicorp/go-retryablehttp

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/repository/pgrepo/pgrepo.go
> +func (repo *PostgresRepo) GetAllOrder(ctx context.Context) ([]entities.Order, error) {
Неудачное имя: мы извлекаем не все, а только необработанные заказы

2023-07-31 15:21 UTC, s-shpak commented on internal/loyalty-accruals/loyalty-accruals.go
> +	for _, order := range allOrder {
Запросы надо посылать не по очереди, а параллельно

2023-07-31 15:21 UTC, s-shpak commented on internal/loyalty-accruals/worker.go
> +				if errorsCounter > 10 {
Я не помню, чтобы ТЗ описывало такое поведение

2023-07-31 15:21 UTC, s-shpak commented on internal/loyalty-accruals/loyalty-accruals.go
> +	if resp.StatusCode != http.StatusOK {
Необходимо учитывать и использовать информацию, которую сервис accrual передает с ошибкой `Too many requests`

2023-07-31 15:21 UTC, s-shpak commented on internal/runner/runner.go
> +	if r.cfq.AccrualAddress != "" {
А если адрес пустой, то есть ли смысл продолжать выполнение?

2023-07-31 15:21 UTC, s-shpak commented on internal/runner/runner.go
> +	if err := r.server.ListenAndServe(); err != nil {
ListenAndServe всегда возвращает ошибку, но, кажется, не всегда ее стоит логировать

2023-07-31 15:21 UTC, s-shpak commented on internal/utils/jwt/jwt.go
> +var key = []byte("secret")
Ключ нельзя сконфигурировать и, кроме того, эта переменная - дупликат ключа из `middleware`

2023-07-31 15:21 UTC, s-shpak commented on internal/logger/logger.go
> +	defer func(logger *zap.Logger) {
Зачем эта функция?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/rest/handlers/handlers.go
> +	requestTimeout = 5 * time.Second
А зачем добавлять таймаут на обрботку запроса таким способом?

Если ты хочешь добавить таймаут, то лучше это делать через конфигурацию сервера

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/rest/handlers/handlers.go
> +func (h *Handler) getUserIDFromBody(w http.ResponseWriter, r *http.Request) (userID int64) {
См. комментарий про ключи контекста

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/repository/pgrepo/pgrepo.go
> +	cryptPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), bcrypt.DefaultCost)
Слой данных не должен выполнять логику приложения: получение хеша надо делать на уровне выше

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/rest/handlers/user.go
> +	if err = h.db.Login(requestContext, &user); err != nil {
Зачем вызывать логин сразу после успешной регистрации?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/rest/handlers/user.go
> +func (h *Handler) Login(w http.ResponseWriter, r *http.Request) {
Кажется, что этот метод практически полностью дублирует `Registration` - их можно объединить

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/repository/repository.go
> +type Storage interface {
Зачем определять интерфейс в этом пакете?

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/repository/pgrepo/pgrepo.go
> +		existOrder, err := repo.CheckOrder(ctx, order.Number)
Этот запрос должен выполняться в рамках начатой транзакции

2023-07-31 15:21 UTC, s-shpak commented on internal/api-go-mart/repository/pgrepo/pgrepo.go
> +	tx, err := repo.db.BeginTx(ctx, nil)
В этом методе ты делаешь один запрос к БД, зачем тебе транзакция?

2023-07-31 15:21 UTC, s-shpak requested changes
1. Автотесты пока не проходят
2. В проекте нет ни одного юнит-теста
3. Почеу ты нигде не использовал сжатие ответа/декомпрессию запроса?

2023-08-03 07:22 UTC, alexlzrv commented on internal/api-go-mart/rest/middleware/jwtauth.go
> +	j "github.com/alexlzrv/go-mart/internal/utils/jwt"
название пакета моего совпадает с внешним

2023-08-03 07:25 UTC, alexlzrv commented on internal/api-go-mart/repository/repository.go
> +type Storage interface {
единый интерфейс для всех бд, которые могут быть, определяю его отдельно, а затем реализую для постгре, если будет другая бд, то реализую его и добавлю только еще одну строку для инициализации

2023-08-03 07:27 UTC, alexlzrv commented on internal/api-go-mart/repository/pgrepo/pgrepo.go
> +	tx, err := repo.db.BeginTx(ctx, nil)
если апдейт не сработает, откат изменения, нет?)

2023-08-05 17:40 UTC, s-shpak requested changes

2023-08-05 17:40 UTC, s-shpak commented on internal/loyalty-accruals/worker.go
> +			err := w.db.UpdateOrder(&entities.Order{Status: entities.OrderStatusProcessing, Number: order.Number})
Осталось последнее исправление: ты делаешь два запроса к БД, а значит, они должны быть сделаны в одной транзакции

2023-08-06 11:05 UTC, s-shpak approved these changes

2023-08-06 11:05 UTC, s-shpak approved these changes

2023-08-06 11:37 UTC, merged